version: '3.8'
services:
  db:
    build: .
    container_name: docker-staff
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shift_manager
      MYSQL_USER: hiro
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./gradle/sql:/docker-entrypoint-initdb.d
      - my-vol:/var/lib/mysql
volumes:
  my-vol:
